export const GET_COUTRIES_REQUEST = 'GET_COUTRIES_REQUEST'
export const GET_COUTRIES_SUCCESS = 'GET_COUTRIES_SUCCESS'
export const GET_COUTRIES_FAILURE = 'GET_COUTRIES_FAILURE'

export const GET_CITIES_REQUEST = 'GET_CITIES_REQUEST'
export const GET_CITIES_SUCCESS = 'GET_CITIES_SUCCESS'
export const GET_CITIES_FAILURE = 'GET_CITIES_FAILURE'

export const GET_WEATHER_REQUEST = 'GET_WEATHER_REQUEST'
export const GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS'
export const GET_WEATHER_FAILURE = 'GET_WEATHER_FAILURE'

export const ADD_CITY = 'ADD_CITY'
export const CHANGE_CURRENT_CITY = 'CHANGE_CURRENT_CITY'
export const DELETE_CURRENT_CITY = 'DELETE_CURRENT_CITY'
export const ADD_SELECTED_CITIES = 'ADD_SELECTED_CITIES' 